### ISSUE TITLE
Table 6 in Table

### ISSUE THREAD

**Issue by ZZWENG** [River-Zhang/SIFU#5]
Hi authors, could you provide some details on your evaluation protocol for Table 6? Specifically, 

1. what is the rendering size? 
2. how many views per subject?
3. which backbone for lpips?

Thank you very much!

**Comment by River-Zhang** [comment]
Thanks for reading our paper. 
1. The rendering size is 512 as the size of GT images in the dataset is 512.
2. We use four views per subject, by rotating {0, 90, 180, 270}. This is the same as our normal loss calculation.
3. We use VGG backbone for lpips calculation.

**Comment by ZZWENG** [comment]
Hi, thank you for your quick response! I plan to compare to your work for an ECCV submission, and since the texture inference code is not out yet, would you mind sharing the original qualitative results without the bounding boxes n Figure 5?

Thank you very much!



On Mar 2, 2024, at 9:56 PM, Zechuan Zhang ***@***.***> wrote:



Thanks for reading our paper.

  1.  The rendering size is 512 as the size of GT images in the dataset is 512.
  2.  We use four views per subject, by rotating {0, 90, 180, 270}. This is the same as our normal loss calculation.
  3.  We use VGG backbone for lpips calculation.

**Comment by River-Zhang** [comment]
Hi, thank you for considering our work for your ECCV submission! Unfortunately, the texture inference code and the original qualitative results from Figure 5 are not currently available for public release. However, the coarse texture prediction is contained in our released code. You can try that by uncommenting the code in apps/infer.py line 709 and 717, use gen_mesh_color() to get the coarse texture.

```bash
         final_colors=gen_mesh_color(verts_pr, model.netG, device, in_tensor)
         final.visual.vertex_colors = final_colors
```
Also, you can use the quantitative results in the paper as a reference. We haven't released the texture refinement stage because it needs GPT-4V and it is not available for everyone. We are looking for alternative ways for a stable, cheap, and effective refinement.
Best wishes for your submission!
