### ISSUE TITLE
Questions about training

### ISSUE THREAD

**Issue by glorioushonor** [River-Zhang/SIFU#6]
GOOD JOB.  several questions about the `code.`
1. The Values of default "mcube_res" is incosistent in two codes.
[https://github.com/River-Zhang/SIFU/blob/ca76e36e929da7dd0f0d7e617bee19867bcfb046/README.md?plain=1#L87](url)
[https://github.com/River-Zhang/SIFU/blob/ca76e36e929da7dd0f0d7e617bee19867bcfb046/configs/train/sifu.yaml#L68](url)

2. I noticed that you modified the rendering script for the dataset. Based on your script, I re-rendered the dataset. I think you modified the script mainly to obtain side-view data of the human body. I want to know if the texture training data was rendered using the script from ICON or from the PIFU training data.  
```
'uv_render_path': osp.join(self.root, render_folder, 'uv_color', f'{rotation:03d}.png'),
'uv_mask_path': uv_mask_path,
'uv_pos_path': uv_pos_path,
'uv_normal_path': osp.join(self.root, render_folder, 'uv_normal', '%02d.png' % (0)),
'image_mask_path':image_mask_path,
'param_path':param_path,
```
3.Are the geometric and texture stages trained together?
`error=BCEloss+color_loss`

4. Will there be a detailed document about the training, as well as the the code of texure reconstruction, including test and inference?

**Comment by River-Zhang** [comment]
Thanks for trying the code. I'll try to answer your questions.
1. The mcube_res in configs/train/sifu.yaml is used in validation during training, not testing or inference. I set it to be small to avoid cuda out of memory.
2. Yes, the texture training data was rendered using the script from PIFu.
3. Yes, they are trained together. However, this only leads to coarse texture. We use diffusion models to refine the texture in our next stage.
4. We haven't released the texture refinement stage because it needs GPT-4V which is not available for everyone. We are looking for alternative ways for a stable, cheap, and effective refinement.

**Comment by glorioushonor** [comment]
> 2\. modified the rendering script

Are the following UV files obtained from the modified rendering script not used?
![image](https://github.com/River-Zhang/SIFU/assets/120625228/5c710e32-fb72-4a0f-b839-0649b7a4f1ef)

**Comment by River-Zhang** [comment]
They are used to get ground truth color sampling around the mesh. We referred to PIFu's dataset code.

**Comment by glorioushonor** [comment]
> They are used to get ground truth color sampling around the mesh. We referred to PIFu's dataset code.

@River-Zhang  Hello, could you please share the modified PIFu's dataset code for rendering the THUman2.0 dataset?
